config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  devise_for :users
  root to: 'rooms#index'
  resources :users, only: [:show, :edit, :update]
  resources :rooms, only: [:create, :destroy] do
    collection do
      get 'search'
    end
    resources :posts do
      collection do
        get 'search'
        get 'favorite'
      end
      resources :comments, only: [:create, :destroy]
      resources :favorites, only: [:create, :destroy]
    end
  end
  resources :room_users, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :room_users
  has_many :rooms, through: :room_users
  has_many :posts
  has_many :comments
  has_many :favorites
  has_one_attached :image

  validates :nickname, presence: true, uniqueness: true, length: { maximum: 15 }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  before_action :move_root, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @favorites = Favorite.where(user_id: current_user.id).order(created_at: 'DESC')
    @favorite_posts = Favorite.favorite_list(@favorites)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :image)
  end

  def move_root
    redirect_to user_path if current_user.id != params[:id].to_i
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<main class="user-edit-wrapper">
  <div class="user-new-form-body">
    <h2>ユーザー編集画面</h2>
    <div class="user-new-form-lists">
      <%= form_with model: [@user], local: true do |f| %>
      <%= render "devise/shared/error_messages", model: f.object %>

        <div class="form-field">
          <label class="form-text">ニックネーム</label>
          <%= f.text_field :nickname, placeholder:"ニックネーム (20文字以内)", maxlength:"20", class:"form-default" %>
        </div>

        <div class="form-field">
          <label class="form-text">ユーザー画像</label>
            <%= f.file_field :image %>
        </div>

        <div class="user-form-btn">
          <%= f.submit "編集", class:"form-blue-btn" %>
        </div>

      <% end %>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<main class="user-wrapper">
  <div class="user-container">

    <div class="user-profile-wrapper">
      <div class="user-profile-container">

        <div class="user-profile-header">
          <div class="user-profile-img">
            <%= render "shared/user-img", user: @user %>
          </div>
          <div class="user-profile-nickname">
            <%= @user.nickname %>
          </div>
          <% if current_user.id == @user.id %>
            <div class="user-profile-edit">
              <%= link_to "プロフィールを変種する", edit_user_path %>
            </div>
          <% end %>
          <div class="user-profile-border"></div>
          <div class="user-profile-show">
            <div class="user-profile-show-box">
              <div class="user-profile-show-item">投稿数</div>
              <div class="user-profile-show-num"><%= Post.where(user_id: @user.id).length %></div>
            </div>
            <div class="user-profile-show-box">
              <div class="user-profile-show-item">お気に入り数</div>
              <div class="user-profile-show-num"><%= Favorite.where(user_id: @user.id).length %></div>
            </div>
          </div>
        </div>

      </div>
    </div>

    <div class="user-screen-wrapper">
      <% if @user.id == current_user.id %>
        <p>参加ルームリスト</p>
        <div class="user-profile-screen-lists">
          <% current_user.rooms.each do |room| %>
            <div class="user-profile-screen-box">
              <div class="user-profile-screen-name">
                <%= link_to room.room_name, room_posts_path(room) %>
              </div>
            </div>
          <% end %>
        </div>

        <p>自分の投稿リスト</p>
        <div class="user-profile-screen-lists">
          <% current_user.posts.each do |post| %>
            <div class="user-profile-screen-box">
              <div class="user-profile-screen-name">
                <%= link_to post.title, room_post_path(post.room_id, post.id) %>
              </div>
            </div>
          <% end %>
        </div>

        <p>お気に入り投稿リスト</p>
        <div class="user-profile-screen-lists">
          <% @favorite_posts.each do |post| %>
            <div class="user-profile-screen-box">
              <div class="user-profile-screen-name">
              <%= link_to post.title, room_post_path(post.room_id, post.id) %>
              </div>
            </div>
          <% end %>
        </div>
      <% else %>
        <div class="user-profile-no-current-user">
          ここにはユーザー本人にのみ、情報が表示されます。
        </div>
      <% end %>
    </div>
  </div>
<main>