config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  devise_for :users
  root to: 'rooms#index'
  resources :users, only: [:show, :edit, :update]
  resources :rooms, only: [:create, :destroy] do
    collection do
      get 'search'
    end
    resources :posts do
      collection do
        get 'search'
        get 'favorite'
      end
      resources :comments, only: [:create, :destroy]
      resources :favorites, only: [:create, :destroy]
    end
  end
  resources :room_users, only: [:create, :destroy]
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users
  has_many :users, through: :room_users, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :favorites

  with_options presence: true do
    validates :room_name, length: { maximum: 20 }
    validates :room_description, length: { maximum: 40 }
    validates :owner_id
  end

  def self.search(search)
    if search != ''
      Room.where('room_name LIKE(?)', "%#{search}%")
    else
      Room.all
    end
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :search]
  before_action :move_root, only: [:destroy]

  def index
    @rooms = Room.all.order(created_at: 'DESC')
    @room = Room.new
    @roomuser = RoomUser.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      render json: { post: @room }
    else
      render json: { post: @room }, status: 422
    end
  end

  def search
    @rooms = Room.search(params[:keyword]).order(created_at: 'DESC')
  end

  def destroy   
    @room.destroy
    redirect_to root_path
  end

  private

  def room_params
    params.require(:room).permit(:room_name, :room_description, user_ids: []).merge(owner_id: current_user.id)
  end
end

def move_root
  @room = Room.find(params[:id])
  redirect_to root_path if current_user.id != @room.owner_id
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_login_index.html.erb
<main class="index-room-container">

  <%= render "shared/left-room-bar" %>

  <div class="room-screen">
    <div class="room-screen-header">
      <div class="room-screen-header-box">
        <h1 class="room-screen-header-title">ようこそ！<%= image_tag "guruttoS_logo.png" %>へ</h1>
        <div class="room-screen-header-search">
          <%= form_with(url: search_rooms_path, local: true, method: :get, class: "search-form") do |form| %>
            <%= form.text_field :keyword, placeholder: "ルーム名を検索する", class: "search-form-text" %>
            <%= form.submit "検索", class: "search-btn" %>
          <% end %>
          </form>
        </div>
      </div>
    </div>

    <div class="room-screen-box">
      <div class="room-screen-lists">

        <% @rooms.each do |room| %>
          <div class="room-screen-list-box">
            <div class="room-screen-list-header">
              <div class="room-screen-list-room-name"><%= room.room_name %></div>
                <div class="room-screen-list-btn">
                  <% unless RoomUser.where(room_id: room.id).exists?(user_id: current_user.id) %>
                    <%= form_with model: @roomuser, local: true do |f| %>
                      <input name="room_user[user_id]" type="hidden" value=<%= current_user.id %>>
                      <input name="room_user[room_id]" type="hidden" value=<%= room.id %>>
                      <%= f.submit "参加", class:"room-entry-btn" %>
                    <% end %>
                  <% else %>
                    <div class="room-exist-btn">
                      <%= link_to "退出", room_user_path(room), method: :delete %>
                    </div>
                  <% end %>
                  <% if room.owner_id == current_user.id %>
                    <div class="room-delete-btn">
                      <%= link_to "削除", room_path(room), method: :delete, data: { confirm: '本当に削除しても良いですか？' } %>
                    </div>
                  <% end %>
                </div>
              </div>
            <div class="room-screen-list-description"><%= room.room_description %></div>
            <div class="room-screen-list-body">
              <div class="room-screen-list-owner-name">オーナー名：<%= link_to User.find(room.owner_id).nickname, user_path(User.find(room.owner_id).id) %></div>
              <div class="room-screen-list-create-date">作成日時：<%= room.created_at.to_s(:datetime_jp) %></div>
            </div>
          </div>
        <% end %>

      </div>
    </div>

  </div>
</main>

app/views/rooms/_room_create_window.html.erb
<div id="modal-room-create" class="modal-room-create">
  <h2 class="modal-room-create-title">ルームの作成</h2>
  <div class="modal-room-create-form-box">
    <%= form_with model: @room, id: 'modal-room-create-form', local: true do |f| %>
      <div class="field">
        <label class="form-text">ルーム名</label>
        <%= f.text_field :room_name, placeholder:"ルーム名 (20文字以内)", maxlength:"20", class:"form-default" %>
      </div>

      <div class="field">
        <label class="form-text">ルーム説明文</label>
        <%= f.text_field :room_description, placeholder:"ルーム説明 (40文字以内)", maxlength:"40", class:"form-default" %>
      </div>

      <input name="room[user_ids][]" type="hidden" value=<%= current_user.id %>>

        <%= f.submit "作成", class:"modal-btn", id:"modal-create-btn" %>
    <% end %>
    <button class="modal-btn modal-cancel-btn" id="room-create-cancel">キャンセル</button>
  </div>
</div>

<div id="modal-overlay" class="modal-overlay"></div>

app/views/rooms/_unlogin_index.html.erb
<main class="index-main-container">
  <h1 class="index-heading"><span>ぐるっとS</span>とは</h1>
  <div class="index-text">
    <p>ぐるっとSは会社やサークルなど、特定のグループ内で</p>
    <p>情報の発信や共有を行うことが出来るWebサービスです。</p>
    <div class="index-btn"><%= link_to "始めてみる", new_user_registration_path %></div>
  </div>
</main>

app/views/rooms/index.html.erb
<% if user_signed_in? %>
  <%= render "rooms/login_index" %>
<% else %>
  <%= render "rooms/unlogin_index" %>
<% end %>

app/views/rooms/new.html.erb
<div class="devise-container">
  <div class="devise-title">
    <h2>ルーム作成</h2>
  </div>
  <div class="devise-form">
    <%= form_with model: @room, local: true do |f| %>
    <%= render "devise/shared/error_messages", model: f.object %>
      <div class="field">
        <label class="form-text">ルーム名</label>
        <%= f.text_field :room_name, placeholder:"ルーム名 (20文字以内)", maxlength:"20", class:"form-default" %>
      </div>

      <div class="field">
        <label class="form-text">ルーム説明文</label>
        <%= f.text_field :room_description, placeholder:"ルーム説明 (100文字以内)", maxlength:"100", class:"form-default" %>
      </div>

      <input name="room[user_ids][]" type="hidden" value=<%= current_user.id %>>

      <div class="register-btn">
        <%= f.submit "作成", class:"register-blue-btn" %>
      </div>
    <% end %>

  </div>
</div>

app/views/rooms/search.html.erb
<% if user_signed_in? %>
  <%= render "rooms/login_index"%>
<% else %>
  <%= render "rooms/unlogin_index"%>
<% end %>