config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  devise_for :users
  root to: 'rooms#index'
  resources :users, only: [:show, :edit, :update]
  resources :rooms, only: [:create, :destroy] do
    collection do
      get 'search'
    end
    resources :posts do
      collection do
        get 'search'
        get 'favorite'
      end
      resources :comments, only: [:create, :destroy]
      resources :favorites, only: [:create, :destroy]
    end
  end
  resources :room_users, only: [:create, :destroy]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :room
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  with_options presence: true do
    validates :title, length: { maximum: 60 }
    validates :content, length: { maximum: 30000 }
  end

  def self.search(search)
    if search != ''
      Post.where('title LIKE(?)', "%#{search}%").or(Post.where('content LIKE(?)', "%#{search}%"))
    else
      Post.all
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :move_root, only: [:edit, :destroy]

  def index
    @room = Room.find(params[:room_id])
    @posts = @room.posts.all.includes(:user).order(created_at: 'DESC')
  end

  def new
    @post = Post.new
    @room = Room.find(params[:room_id])
  end

  def create
    @room = Room.find(params[:room_id])
    @post = @room.posts.new(post_params)
    if @post.save
      redirect_to room_posts_path
    else
      render :new
    end
  end

  def show
    @room = Room.find(params[:room_id])
    @post = @room.posts.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.all.includes(:user)
    @favorite = Favorite.find_by(user_id: current_user.id, post_id: @post.id)
  end

  def edit
    @room = Room.find(params[:room_id])
    @post = @room.posts.find(params[:id])
  end

  def update
    @room = Room.find(params[:room_id])
    @post = @room.posts.find(params[:id])
    if @post.update(post_params)
      redirect_to room_post_path
    else
      render :new
    end
  end

  def destroy
    @room = Room.find(params[:room_id])
    @post = @room.posts.find(params[:id])
    @post.destroy
    redirect_to room_post_path
  end

  def search
    @room = Room.find(params[:room_id])
    @posts = @room.posts.search(params[:keyword]).includes(:user).order(created_at: 'DESC')
  end

  def favorite
    @room = Room.find(params[:room_id])
    @favorites = @room.favorites.where(user_id: current_user.id).order(created_at: 'DESC')
    @posts = Favorite.favorite_list(@favorites)
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :ref_url).merge(room_id: params[:room_id], user_id: current_user.id)
  end

  def move_root
    @post = Post.find(params[:id])
    @user = User.find(@post.user_id)
    redirect_to root_path if current_user.id != @user.id
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_left-post-bar.html.erb
<div class="default-left-bar">
  <div class="default-left-bar-box">
    <p class="default-left-bar-name">
      <%= link_to user_path(current_user.id) do %>
        <div class="user-img-min"><%= render "shared/user-img", user: current_user %></div>
        <%= current_user.nickname %>
      <% end %>
    </p>
  </div>
  <div class="default-left-bar-boder"></div>
  <div class="default-left-create-box">
    <div class="default-left-create-btn" ><%= link_to "投稿する",new_room_post_path %></div>
    <%= render "rooms/room_create_window" %>
  </div>
  <div class="default-left-lists-header">投稿メニュー</div>

  <div class="post-left-lists">
    <div class="post-left-list-box">
      <div class="post-left-list-item">
        <ol>
          <li><%= link_to "投稿一覧", room_posts_path %></li>
          <li><%= link_to "お気に入り一覧", favorite_room_posts_path %></li>
        </ol>
      </div>
    </div>
  </div>
</div>

app/views/posts/_post-new-form-body.html.erb
<div class="post-new-form-body">
  <div class="post-new-form-lists">
    <%= form_with model: [@room, @post], local: true do |f| %>
    <%= render "devise/shared/error_messages", model: f.object %>
      <div class="form-field">
        <label class="form-text">投稿タイトル</label>
        <%= f.text_field :title, placeholder:"投稿タイトル (60文字以内)", maxlength:"60", class:"post-form-box" %>
      </div>

      <div class="form-field">
        <label class="form-text">本文</label>
        <%= f.text_area :content, placeholder:"本文を入力してください（Markdown記法が利用可能です）", maxlength:"10000", class:"post-form-content" %>
      </div>

      <div class="post-form-btn">
        <%= f.submit "作成", class:"form-blue-btn" %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/_post-screen-box.html.erb
<div class="post-screen-box">
  <div class="post-screen-lists">
    <% if @posts.any? %>
      <div class="post-screen-lists-border"></div>
    <% end %>
    <% @posts.each do |post| %>
      <div class="post-screen-list-box">
        <div class="post-screen-list-header">
          <%= link_to post.title, room_post_path(@room, post) %>
        </div>
        <div class="post-screen-list-body">
          投稿者：<%= link_to post.user.nickname, user_path(post.user.id), class:"post-screen-list-user" %>　投稿日時：<%= post.created_at.to_s(:datetime_jp) %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/_post-screen-header.html.erb
<div class="post-screen-header">
  <div class="post-screen-header-box">
    <div class="post-screen-header-title">
      ルーム：<%=link_to @room.room_name, room_posts_path, class:"post-screen-header-room-name" %>
    </div>
    <div class="post-screen-header-search">
      <%= form_with(url: search_room_posts_path, local: true, method: :get, class: "post-search-form") do |form| %>
        <%= form.text_field :keyword, placeholder: "調べたいワードを入力してください", class: "post-search-form-text" %>
        <%= form.submit "検索", class: "search-btn" %>
      <% end %>
      </form>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="post-new-form-container">

  <%= render "posts/left-post-bar"%>

  <div class="post-form-wrapper">

  <%= render "posts/post-screen-header"%>
  <%= render "posts/post-new-form-body"%>

  </div>
</div>

app/views/posts/favorite.html.erb
<main class="index-post-container">
  <%= render "posts/left-post-bar" %>

  <div class="post-screen">
    <%= render "posts/post-screen-header" %>
    <h4 class="post-screen-title">お気に入り登録一覧</h4>
    <%= render "posts/post-screen-box" %>
  </div>
</main>

app/views/posts/index.html.erb
<main class="index-post-container">
  <%= render "posts/left-post-bar" %>

  <div class="post-screen">
    <%= render "posts/post-screen-header" %>
    <h4 class="post-screen-title">投稿一覧</h4>
    <%= render "posts/post-screen-box" %>
  </div>
</main>

app/views/posts/new.html.erb
<div class="post-new-form-container">

  <%= render "posts/left-post-bar"%>

  <div class="post-form-wrapper">

  <%= render "posts/post-screen-header"%>
  <%= render "posts/post-new-form-body"%>

  </div>
</div>

app/views/posts/search.html.erb
<main class="index-post-container">
  <%= render "posts/left-post-bar" %>

  <div class="post-screen">
    <%= render "posts/post-screen-header" %>
      <h4 class="post-screen-title">検索結果</h4>
    <%= render "posts/post-screen-box" %>
  </div>
</main>

app/views/posts/show.html.erb
<main class="index-post-container">
  <%= render "posts/left-post-bar" %>

  <div class="post-show-screen">
    <%= render "posts/post-screen-header" %>

    <div class="post-screen-show-box">
      <div class="post-screen-show-header">
        <div class="post-screen-show-header-top">
          <p class="post-screen-show-user">
            <%= link_to user_path(@post.user.id) do %>
              <div class="user-img-min"><%= render "shared/user-img", user: @post.user %></div>
              <%= @post.user.nickname %>
            <% end %>
          </p>
          <div class="post-screen-show-postdate">
            <<%= @post.created_at.to_s(:datetime_jp) %>に投稿>
          </div>
          <% if current_user.id == @post.user.id %>
            <div class="post-screen-show-edit">
              <%= link_to "編集", edit_room_post_path(@room, @post) %>
            </div>
            <div class="post-screen-show-destroy">
              <%= link_to "削除", room_post_path(@room, @post), method: :delete %>
            </div>
          <% end %>
        </div>
        <div class="post-screen-show-title">
          <%= @post.title %>
        </div>
        <div class="post-screen-show-favorite">
          <% if @favorite == nil %>
            <%= link_to "お気に入りに登録する", room_post_favorites_path(@room, @post), method: :create %>
          <% else %>
            <%= link_to "お気に入りを解除する", "/rooms/#{@room.id}/posts/#{@post.id}/favorites/#{@favorite.id}", method: :delete %>
          <% end %>
        </div>
      </div>
      <div class="post-screen-show-body">
        <div class="post-screen-show-body">
          <div class="post-screen-show-body-border">投稿内容</div>
          <div class="post-screen-show-content"><%= markdown(@post.content).html_safe %></div>
          <div class="post-screen-show-body-border">コメント</div>
          <div class="post-screen-show-comment-area">
            <% @comments.each do |comment| %>
              <div class="comment-area-box">
                <div class="comment-area-message"><%= comment.message %></div>
                <div class="comment-area-footer">
                  <p class="comment-area-user">
                    <%= link_to user_path(comment.user.id) do %>
                    <div class="user-img-min"><%= render "shared/user-img", user: comment.user %></div>
                    <%= comment.user.nickname %>
                    <% end %>
                  </p>
                  <div class="comment-area-message-date">投稿日時:<%= comment.created_at.to_s(:datetime_jp) %></div>
                  <% if comment.user.id == current_user.id %>
                    <div class="comment-area-delete"><%= link_to "削除", "/rooms/#{@room.id}/posts/#{comment.post_id}/comments/#{comment.id}", method: :delete %></div>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
          <div class="post-screen-show-comment-form">
            <p>■コメントを投稿する</p>
            <%= form_with model: [@room, @post, @comment], local: true do |f| %>
              <div class="comment-form-error-messages"><%= render "devise/shared/error_messages", model: f.object %></div>
              <%= f.text_area :message, class: 'comment-form-box', placeholder: 'コメントを入力してください', maxlength:"1000" %>
            <%= f.submit '送信', class: 'comment-form-submit' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>

  </div>
</main>